// Code generated by mockery v1.0.0. DO NOT EDIT.

package job

import mock "github.com/stretchr/testify/mock"
import time "time"

// MockCollector is an autogenerated mock type for the Collector type
type MockCollector struct {
	mock.Mock
}

// CollectChangedAppts provides a mock function with given fields: _a0
func (_m *MockCollector) CollectChangedAppts(_a0 time.Time) ([]*ApptChange, error) {
	ret := _m.Called(_a0)

	var r0 []*ApptChange
	if rf, ok := ret.Get(0).(func(time.Time) []*ApptChange); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*ApptChange)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(time.Time) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
